#include<iostream>
#include<fstream>
#include<math.h>
using namespace std;

#define PI 3.14159265
int build_environment_map(){
// To initialize all the parameters by using data in the figure above.

double x0[5]={0.8, 0.8, 1.7, 2.2, 2.25}; //x axis points
double y0[5]={1.5, 2.25, 1.0, 1.3, 0.25}; //y axis points
double radius=0.125, wallLength=2.5;
double RD=PI/180; 
// Opens a data file called “EnvironmentMap.txt” for storing walls, pillars and charger generated by the code.

ofstream map;
map.open("EnvironmentMap.txt");

// The followingcode is to create a charger based on its centre.
for (int i=0; i<360; i=i+20) {
map<<x0[4]+radius*cos(i*RD)<<' '<<y0[4]+radius*sin(i*RD)<<endl;
}

// Generates 4 circle pillars with the given centres.
for (int i=0; i<360; i++) {
map<<x0[0]+radius*cos(i*RD)<<' '<<y0[0]+radius*sin(i*RD)<<endl;
}
for (int i=0; i<360; i++) {
map<<x0[1]+radius*cos(i*RD)<<' '<<y0[1]+radius*sin(i*RD)<<endl;
}
for (int i=0; i<360; i++) {
map<<x0[2]+radius*cos(i*RD)<<' '<<y0[2]+radius*sin(i*RD)<<endl;
}
for (int i=0; i<360; i++) {
map<<x0[3]+radius*cos(i*RD)<<' '<<y0[3]+radius*sin(i*RD)<<endl;
}

// Used to generate 2 walls.
for(double j=0 ; j<wallLength; j=j+0.01){
map << j <<' '<< 0 << endl;}
for(double j=0 ; j<wallLength; j=j+0.01){
map << wallLength <<' '<< j << endl;}
// code below generates the other 2 walls
for(double j=0 ; wallLength>j; j=j+0.01){
map << j <<' '<< 2.5 << endl;}
for(double j=0 ; wallLength>j; j=j+0.01){
map << 0 <<' '<< j << endl;}


map.close();
return 0;
}

// Main function into your code for compilation
int main(int argc, char **argv) 
{
int i;
i = build_environment_map();
return 0;
}
